### ISSUE TITLE
Chữa bài 10 - BTVN buổi 2

### ISSUE THREAD

**Issue by HXThai** [tieulac305/ChuDuongPhuongNam_BTVN_Java#1]
Bài 10 đâu e?

**Comment by tieulac305** [comment]
Ghi chú là làm ít nhất 7 bài thôi mà anh, bài 10 còn nâng cao :'(

**Comment by HXThai** [comment]
Toàn bài dễ mà e, làm đuê :))

**Comment by tieulac305** [comment]
Anh à dù s cũng k bắt buộc mà hì :3

**Comment by tieulac305** [comment]
Chiều mai làm được thì em làm anh ạ :3
