### ISSUE TITLE
Sau dùng tiếng nào thì theo tiếng đấy luôn nhé. Đặt tên biến lúc ta lúc tây. Code thành phố lên, quê quá :))

### ISSUE THREAD

**Issue by GuardianOfGods** [tieulac305/ChuDuongPhuongNam_BTVN_Java#2]
https://github.com/tieulac305/ChuDuongPhuongNam_BTVN_Java/blob/02b86f933ad1c40bfc24e009209cc8ffac0557e3/Day%206/btl/src/common/TranDau.java#L5-L7

**Comment by tieulac305** [comment]
cái nào ngắn hơn mà tiện tay thì em dùng thôi anh ạ :3
