### ISSUE TITLE
class KyNang ok

### ISSUE THREAD

**Issue by GuardianOfGods** [tieulac305/ChuDuongPhuongNam_BTVN_Java#3]
https://github.com/tieulac305/ChuDuongPhuongNam_BTVN_Java/blob/02b86f933ad1c40bfc24e009209cc8ffac0557e3/Day%206/btl/src/common/KyNang.java#L1-L23

**Comment by tieulac305** [comment]
ok anh thế cũng tạo issue, sang lên chứ anh -.-
