### ISSUE TITLE
Phần này nên cụ thể hơn. Cho bắt đầu trận đấu rồi nó tự làm mọi thứ.

### ISSUE THREAD

**Issue by GuardianOfGods** [tieulac305/ChuDuongPhuongNam_BTVN_Java#5]
https://github.com/tieulac305/ChuDuongPhuongNam_BTVN_Java/blob/02b86f933ad1c40bfc24e009209cc8ffac0557e3/Day%206/btl/src/app/App.java#L37-L38

**Comment by GuardianOfGods** [comment]
```
public void startFighting() {
        while (!battleWasEnded()) {
            attack();
        }
        System.out.println(getWinner());
    }
```
- Với phương thức Attack là 2 bọn đánh nhau.

**Comment by tieulac305** [comment]
Em push cái anh xem ok k

**Comment by GuardianOfGods** [comment]
Ok em được rồi đấy CLOSE ISSUES thôi ✌️
